### ISSUE TITLE
Facets not displaying with own solr server (4.2.1)

### ISSUE THREAD

**Issue by Treggats** [fergiemcdowall/solrstrap#4]
When using my own solr server version 4.2.1 I get the following facet counts

``` json
  "facet_counts":{
    "facet_queries":{},
    "facet_fields":{
      "type":{
        "text/html":23123,
        "application/pdf":8},
      "host":{
        "example6.nl":6598,
        "nl.example.org":6597,
        "www.example5.nl":2553,
        "www.example4.nl":1923,
        "www.example3.nl":1563,
        "www.example2.nl":1329,
        "www.example1.nl":558,
        "www.example.nl":500},
      "cat":{},
      "lang":{
        "nl":22850,
        "af":201,
        "en":37,
        "it":12,
        "de":10,
        "cs":4,
        "da":3,
        "ro":3}},
    "facet_dates":{},
    "facet_ranges":{}}
```

the facet counts from the example app:

``` json
 "facet_counts":{
  "facet_queries":{},
  "facet_fields":{
    "topics":[
     "earn",3987,
     "acq",2448,
     "money-fx",801,
     "crude",634,
     "grain",628,
     "trade",551,
     "interest",513,
     "wheat",306,
     "ship",305,
     "corn",253,
     "dlr",217,
     "oilseed",192,
     "money-supply",190,
     "sugar",184,
     "gnp",163,
     "coffee",145,
     "veg-oil",137,
     "gold",135,
     "nat-gas",130,
     "soybean",120],
    "organisations":[
     "ec",349,
     "imf",106,
     "opec",93,
     "worldbank",87,
     "gatt",80,
     "ico-coffee",56,
     "oecd",50,
     "icco",44,
     "adb-asia",20,
     "itc",12,
     "adb-africa",10,
     "un",10,
     "unctad",9,
     "fao",8,
     "eib",7,
     "inro",7,
     "iea",6,
     "ida",4,
     "iwc-wheat",4,
     "atpc",3]},
  "facet_dates":{}}
```

What version are you running? Or is the syntax of the facets configurable?

**Comment by fergiemcdowall** [comment]
Go into js/solrstrap.js and change line 8.

Your Solr facets can be read with 

``` javascript
    var FACETS = ['type','host','cat','lang'];
```

**Comment by Treggats** [comment]
Nope thats not it, I saw that already and changed them accordingly.
If you look closely at our facets, they differ in syntax

**Comment by fergiemcdowall** [comment]
Ah- yes, I see that your facets are arranged more sensibly as an array of tuples, whereas the demo is simply an array.

This comes down to the "makeNavsSensible" function.

I have a feeling that your navs are in the right format already, and you can simply remove the makeNavsSensible call from js/solrstrap.js:105. As a last resort you can hack makeNavsSensible to get the nav array into the right format.

So try this at js/solrstrap.js:105

``` javascript
   title: k, navs: result.facet_counts.facet_fields[k]}));
```

**Comment by EivindEE** [comment]
We could add a check for Array/Object before the makeNavsSensible function is called, then it could work with both return types.

**Comment by fergiemcdowall** [comment]
Good idea @EivindEE - there could be a check for solr version which would then determine an appropriate makeNavsSensible function.

**Comment by Treggats** [comment]
The query string needs the following with the current code

``` javascript
&json.nl=flat
```

See http://wiki.apache.org/solr/SolJSON

**Comment by fergiemcdowall** [comment]
Wow- good find @Treggats - that option had completely passed me by!

json.nl=map is the best format. I will update the next version to use json.nl=map , and do away with the makeNavsSensible function.

**Comment by fergiemcdowall** [comment]
But yes, for the current version you need &json.nl=flat in the query URL
