### ISSUE TITLE
Dynamically reload result section on facet select

### ISSUE THREAD

**Issue by janhoy** [fergiemcdowall/solrstrap#5]
Instead of reloading the whole page when someone clicks a facet, only the relevant section(s) of the page should reload in AJAX fashion, i.e. probably use # style URLs to hold the state

**Comment by fergiemcdowall** [comment]
Is there a way to do this without creating a lot of technical overhead?

I wonder if its possible to do something clever with HTTP cache headers to get a similar result... http://www.mnot.net/cache_docs/

**Comment by janhoy** [comment]
Guess that instead of a simple `<a href>` tag for the facets, you could reference a JavaScript function which executes the new query as AJAX, gets the JSON, and then updates only the `<div>` tags that need updating?

**Comment by Treggats** [comment]
@fergiemcdowall if you want to do something with cache, look at the solr wiki page http://wiki.apache.org/solr/SolrCaching

**Comment by fergiemcdowall** [comment]
@Treggats interesting, although solr caching is unfortunately outside of Solrstrap's control.

For SolrStrap it seems that the biggest gains to latency and network traffic can be had by setting the cache-control headers. Especially if it's possible to set them for calls to the Solr HTTP endpoint.

**Comment by fergiemcdowall** [comment]
@janhoy I am still getting over the trauma of programming that for http://tilbudssok.posten.no/ and http://www.rettsdata.no/ . It can of course be done, its just that it adds so many more moving parts to the system.

\* shiver *

Having said that, its entirely possible that somebody has a really elegant and simple way of doing this.

**Comment by rwiker** [comment]
Take a look at query.bbq - this takes a lot of the pain out of handling state via the url.

**Comment by fergiemcdowall** [comment]
OK- will do!

**Comment by rwiker** [comment]
I've just implemented this on my fork, using jquery.bbq. This makes for a noticeable speed improvement, and should also make use of navigators a little more robust. Note: I also changed index.html to get jquery, bootstrap, handlebars &c from cdnjs.com, instead of using local copies...

**Comment by fergiemcdowall** [comment]
Hi!

Yes, its a lot faster, but it might be a bit broken? If I type in "new york" and then click on any "topics" navigator- the app seems to grey out and hang...

F

**Comment by rwiker** [comment]
On Aug 21, 2013, at 15:46 , Fergus McDowall notifications@github.com wrote:

> Hi!
> 
> Yes, its a lot faster, but it might be a bit broken? If I type in "new york" and then click on any "topics" navigator- the app seems to grey out and hang...
> 
> Might be browser-dependent, or timing-dependent... I'll see if I can reproduce this behaviour. What browser are you using?

Note: I had to clear out "temporary files" (a.k.a. cached javascript files) several times when I was working on this - did you try that?

**Comment by fergiemcdowall** [comment]
Its definitely broken. I just tested on OSX and windows- exact same error.

**Comment by fergiemcdowall** [comment]
Although I should take some responsibility for not creating a test suite! :)

**Comment by rwiker** [comment]
On Aug 21, 2013, at 17:36 , Fergus McDowall notifications@github.com wrote:

> Its definitely broken. I just tested on OSX and windows- exact same error.
> 
> —
> Reply to this email directly or view it on GitHub.

Ok, I see it... I can reproduce the error by typing "new york" (without quotes) in the inpout field, then clicking a facet value without typing enter. What happens then is that the url will contain an fq value, but no value for q. I guess the correct way to handle this is to add a value for "q" unless there is one already (in add_nav).

**Comment by rwiker** [comment]
I've committed a fix for this problem to my fork - basically, adding a "change" handler to the q input field. I've also added some code to handle empty or all-whitespace queries. It's a lot better than it was earlier today, but probably not perfect.

**Comment by fergiemcdowall** [comment]
Wow- looks great! As far as I can see it works perfectly

If you update your pull request I will merge it into the main solrstrap

**Comment by rwiker** [comment]
I've pushed some more changes - do I need to do anything specific to update the pull request (I'm not a git expert, as you might guess :-)

**Comment by fergiemcdowall** [comment]
You just have to open a new one. The existing pull request includes changes up until the point at which it was made. To include your bug fixes from the intervening period, a new pull request must be made.

**Comment by rwiker** [comment]
It looks to me as if changes commited to the fork after the pull request
are automatically added to the pull request; anyway, I am unable to create
a new pull request as long as the current one exists. If you merge the
current pull request, I could create a new one afterwards, with the rest of
the changes (if necessary)?

I suddenly realised why I see a "Merge Pull Request" button when I look at
the pull request in your repository - it took me a little while to realise
that I actually have permissions to do that myself...

**Comment by janhoy** [comment]
If you continue to commit to your feature branch which the pull request is based on, all changes will be included when Fergie merges the pull request in. Sweet system this GitHub :)

**Comment by fergiemcdowall** [comment]
Bra presisering @janhoy !

Merging now...
